### ISSUE TITLE
Scheduling Crashes Homebridge

### ISSUE THREAD

**Issue by ryan-peterson** [Tommrodrigues/homebridge-web-sprinkler#11]
I recently applied the upgrade from 1.7.4 to 1.7.5 and Homebridge now crashes due to homebridge-web-sprinklers. I tried rolling back to 1.7.4 but the crash problem remains. I have narrowed the problem down to the scheduling function because if I set disableScheduling to true, Homebridge works fine and I can manually control the sprinklers. As soon as disableScheduling is set to false, Homebridge continually crashes and restarts. The Homebridge error log contains the following:

ReferenceError: json is not defined
    at WebSprinklers.<anonymous> (/usr/local/lib/node_modules/homebridge-web-sprinklers/index.js:180:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-web-sprinklers/index.js:111:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-web-sprinklers/node_modules/request/request.js:185:22)
    at Request.emit (node:events:365:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-web-sprinklers/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:365:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-web-sprinklers/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:471:28)
    at IncomingMessage.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)

**Comment by phenotypic** [comment]
Hi there, thank you for bringing this to my attention.

The error you experienced resulted from a faulty variable declaration in the scheduling function. I have resolved the issue in the latest version of the plugin (`1.7.6`).
